services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: incident
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama_init:
    image: ollama/ollama
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        until ollama list >/dev/null 2>&1; do
          echo 'waiting for ollama...';
          sleep 2;
        done;
        ollama pull llama3
      "

volumes:
  pgdata:
  ollama_data: